# Generated by Django 6.0.8 on 2026-08-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("showcase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariorun",
            name="run",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
    ]
