# Generated by Django 5.2.9 on 2026-01-04 11:28

import django.core.serializers.json
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QraftTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "q2_task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Django-Q2 task ID (matches Task.id)",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "func",
                    models.CharField(
                        help_text="Dotted path to the task function", max_length=256
                    ),
                ),
                (
                    "task_args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Task positional arguments",
                    ),
                ),
                (
                    "task_kwargs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Task keyword arguments",
                    ),
                ),
                (
                    "success_hook",
                    models.CharField(
                        blank=True,
                        help_text="Success hook function name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "success_args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Success hook arguments",
                    ),
                ),
                (
                    "success_kwargs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Success hook keyword arguments",
                    ),
                ),
                (
                    "failure_hook",
                    models.CharField(
                        blank=True,
                        help_text="Failure hook function name",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "failure_args",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Failure hook arguments",
                    ),
                ),
                (
                    "failure_kwargs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Failure hook keyword arguments",
                    ),
                ),
                (
                    "retry_policy",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Retry policy configuration",
                    ),
                ),
                (
                    "current_attempt",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Current attempt number"
                    ),
                ),
            ],
            options={
                "verbose_name": "Qraft Task",
                "verbose_name_plural": "Qraft Tasks",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="HookTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parent_task_id",
                    models.UUIDField(
                        db_index=True, help_text="QraftTask.id that triggered this hook"
                    ),
                ),
                (
                    "hook_type",
                    models.CharField(
                        help_text="Type of hook: 'success' or 'failure'", max_length=10
                    ),
                ),
                (
                    "hook_path",
                    models.CharField(
                        help_text="Dotted path to hook function", max_length=256
                    ),
                ),
                (
                    "q2_task_id",
                    models.CharField(
                        help_text="Django-Q2 task ID of the queued hook",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hook Task",
                "verbose_name_plural": "Hook Tasks",
                "ordering": ["-date_created"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("parent_task_id", "hook_type"),
                        name="unique_hook_per_task_type",
                    )
                ],
            },
        ),
    ]
