# Generated by Django 5.2.9 on 2026-01-04 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qraft", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HookDispatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hook_type",
                    models.CharField(
                        help_text="Type of hook: 'success' or 'failure'", max_length=10
                    ),
                ),
                (
                    "hook_path",
                    models.CharField(
                        help_text="Dotted path to hook function", max_length=256
                    ),
                ),
                (
                    "q2_task_id",
                    models.CharField(
                        help_text="Django-Q2 task ID of the queued hook",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hook Dispatch",
                "verbose_name_plural": "Hook Dispatches",
                "ordering": ["-date_created"],
            },
        ),
        migrations.CreateModel(
            name="QraftTaskAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(
                        help_text="Attempt number (1-based)"
                    ),
                ),
                (
                    "q2_task_id",
                    models.CharField(
                        db_index=True,
                        help_text="Django-Q2 task ID for this attempt",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        help_text="True if succeeded, False if failed, null if pending/running",
                        null=True,
                    ),
                ),
                (
                    "exception_class",
                    models.CharField(
                        blank=True,
                        help_text="Exception class name if failed",
                        max_length=256,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "date_completed",
                    models.DateTimeField(
                        blank=True, help_text="When the attempt completed", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Qraft Task Attempt",
                "verbose_name_plural": "Qraft Task Attempts",
                "ordering": ["attempt_number"],
            },
        ),
        migrations.DeleteModel(
            name="HookTask",
        ),
        migrations.RemoveField(
            model_name="qrafttask",
            name="current_attempt",
        ),
        migrations.RemoveField(
            model_name="qrafttask",
            name="q2_task_id",
        ),
        migrations.AddField(
            model_name="qrafttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("exhausted", "Exhausted"),
                ],
                db_index=True,
                default="pending",
                help_text="Current task status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="hookdispatch",
            name="qraft_task",
            field=models.ForeignKey(
                help_text="QraftTask that triggered this hook",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hook_dispatches",
                to="qraft.qrafttask",
            ),
        ),
        migrations.AddField(
            model_name="qrafttaskattempt",
            name="qraft_task",
            field=models.ForeignKey(
                help_text="Parent QraftTask this attempt belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="qraft.qrafttask",
            ),
        ),
        migrations.AddConstraint(
            model_name="hookdispatch",
            constraint=models.UniqueConstraint(
                fields=("qraft_task", "hook_type"),
                name="unique_hook_dispatch_per_task_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="qrafttaskattempt",
            constraint=models.UniqueConstraint(
                fields=("qraft_task", "attempt_number"), name="unique_attempt_per_task"
            ),
        ),
    ]
