# Generated by Django 5.2.9 on 2026-08-04 20:18

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0002_retry_redesign'),
    ]

    operations = [
        migrations.CreateModel(
            name='QraftBatchModel',
            fields=[
                ('success_hook', models.CharField(blank=True, help_text='Success hook function name', max_length=256, null=True)),
                ('success_args', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Success hook arguments')),
                ('success_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Success hook keyword arguments')),
                ('failure_hook', models.CharField(blank=True, help_text='Failure hook function name', max_length=256, null=True)),
                ('failure_args', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Failure hook arguments')),
                ('failure_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Failure hook keyword arguments')),
                ('on_cancelled', models.CharField(blank=True, help_text='Hook called when workflow is cancelled', max_length=256, null=True)),
                ('progress_hook', models.CharField(blank=True, help_text='Hook called on each task completion (parallel workflows only)', max_length=256, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current batch status', max_length=20)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total number of tasks in this batch')),
                ('completed_count', models.PositiveIntegerField(default=0, help_text='Number of tasks completed (success or exhausted)')),
                ('success_count', models.PositiveIntegerField(default=0, help_text='Number of tasks that succeeded')),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of tasks that failed (exhausted)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qraft Batch',
                'verbose_name_plural': 'Qraft Batches',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='QraftChainModel',
            fields=[
                ('success_hook', models.CharField(blank=True, help_text='Success hook function name', max_length=256, null=True)),
                ('success_args', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Success hook arguments')),
                ('success_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Success hook keyword arguments')),
                ('failure_hook', models.CharField(blank=True, help_text='Failure hook function name', max_length=256, null=True)),
                ('failure_args', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Failure hook arguments')),
                ('failure_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Failure hook keyword arguments')),
                ('on_cancelled', models.CharField(blank=True, help_text='Hook called when workflow is cancelled', max_length=256, null=True)),
                ('progress_hook', models.CharField(blank=True, help_text='Hook called on each task completion (parallel workflows only)', max_length=256, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current chain status', max_length=20)),
                ('current_step_index', models.PositiveSmallIntegerField(default=0, help_text='Index of the currently executing step')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qraft Chain',
                'verbose_name_plural': 'Qraft Chains',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='QraftIterModel',
            fields=[
                ('success_hook', models.CharField(blank=True, help_text='Success hook function name', max_length=256, null=True)),
                ('success_args', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Success hook arguments')),
                ('success_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Success hook keyword arguments')),
                ('failure_hook', models.CharField(blank=True, help_text='Failure hook function name', max_length=256, null=True)),
                ('failure_args', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Failure hook arguments')),
                ('failure_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Failure hook keyword arguments')),
                ('on_cancelled', models.CharField(blank=True, help_text='Hook called when workflow is cancelled', max_length=256, null=True)),
                ('progress_hook', models.CharField(blank=True, help_text='Hook called on each task completion (parallel workflows only)', max_length=256, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current iter status', max_length=20)),
                ('func', models.CharField(help_text='Dotted path to the task function', max_length=256)),
                ('default_qraft_options', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Default Qraft options for all tasks')),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total number of tasks in this iter')),
                ('completed_count', models.PositiveIntegerField(default=0, help_text='Number of tasks completed (success or exhausted)')),
                ('success_count', models.PositiveIntegerField(default=0, help_text='Number of tasks that succeeded')),
                ('failure_count', models.PositiveIntegerField(default=0, help_text='Number of tasks that failed (exhausted)')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qraft Iter',
                'verbose_name_plural': 'Qraft Iters',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='counted',
            field=models.BooleanField(default=False, help_text='Whether this attempt has been counted by a parallel dispatcher'),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='qraft_batch',
            field=models.ForeignKey(blank=True, help_text='Parent QraftBatch workflow (if part of batch)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='qraft.qraftbatchmodel'),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='qraft_iter',
            field=models.ForeignKey(blank=True, help_text='Parent QraftIter workflow (if part of iter)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='qraft.qraftitermodel'),
        ),
        migrations.CreateModel(
            name='WorkflowHookDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_type', models.CharField(help_text="Type of workflow: 'chain', 'iter', or 'batch'", max_length=10)),
                ('workflow_id', models.UUIDField(db_index=True, help_text='UUID of the workflow (chain/iter/batch)')),
                ('hook_type', models.CharField(help_text="Type of hook: 'success' or 'failure'", max_length=10)),
                ('hook_path', models.CharField(help_text='Dotted path to hook function', max_length=256)),
                ('q2_task_id', models.CharField(help_text='Django-Q2 task ID of the queued hook', max_length=32, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Workflow Hook Dispatch',
                'verbose_name_plural': 'Workflow Hook Dispatches',
                'ordering': ['-date_created'],
                'constraints': [models.UniqueConstraint(fields=('workflow_type', 'workflow_id', 'hook_type'), name='unique_workflow_hook_dispatch')],
            },
        ),
        migrations.CreateModel(
            name='QraftChainStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.PositiveSmallIntegerField(help_text='Zero-based index of this step in the chain')),
                ('func', models.CharField(help_text='Dotted path to the task function', max_length=256)),
                ('task_args', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Task positional arguments')),
                ('task_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Task keyword arguments')),
                ('qraft_options', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Qraft-specific options (retry policy, etc.)')),
                ('chain', models.ForeignKey(help_text='Parent chain this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='qraft.qraftchainmodel')),
                ('qraft_task', models.OneToOneField(blank=True, help_text='QraftTask instance once step is queued', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chain_step', to='qraft.qrafttask')),
            ],
            options={
                'verbose_name': 'Qraft Chain Step',
                'verbose_name_plural': 'Qraft Chain Steps',
                'ordering': ['step_index'],
                'constraints': [models.UniqueConstraint(fields=('chain', 'step_index'), name='unique_chain_step')],
            },
        ),
    ]
