# Generated by Django 5.2.9 on 2026-08-04 20:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0003_workflow_primitives'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('tokens', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rate Bucket',
                'verbose_name_plural': 'Rate Buckets',
            },
        ),
        migrations.AddField(
            model_name='qraftchainstep',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Chain parks in WAITING_APPROVAL before running this step'),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Caller-supplied key; re-enqueueing the same key is a no-op', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('default', 'Default'), ('low', 'Low')], db_index=True, default='default', help_text='Priority lane within the consuming cluster', max_length=10),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='progress',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Task-reported progress payload (current/total/message)', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='usage',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Task-reported usage (model, input_tokens, output_tokens, cost)', null=True),
        ),
        migrations.AlterField(
            model_name='qraftbatchmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting for approval'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current batch status', max_length=20),
        ),
        migrations.AlterField(
            model_name='qraftchainmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting for approval'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current chain status', max_length=20),
        ),
        migrations.AlterField(
            model_name='qraftitermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_approval', 'Waiting for approval'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current iter status', max_length=20),
        ),
    ]
