# Generated by Django 6.0.8 on 2026-08-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0004_ai_workload_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='date_started',
            field=models.DateTimeField(blank=True, help_text='When a worker began executing this attempt', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last execution-lease heartbeat from the running worker', null=True),
        ),
    ]
