# Generated by Django 6.0.8 on 2026-08-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0006_scheduler_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='worker_pid',
            field=models.IntegerField(blank=True, help_text='OS pid of the worker process that executed this attempt', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='worker_thread',
            field=models.CharField(blank=True, help_text='Executor thread name within the worker process; blank for standard (non-threaded) workers', max_length=64, null=True),
        ),
    ]
