# Generated by Django 6.0.8 on 2026-08-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0007_worker_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrafttaskattempt',
            name='q2_task_id',
            field=models.CharField(blank=True, help_text='Django-Q2 task ID for this attempt; null until a dispatcher enqueues a SCHEDULED attempt', max_length=32, null=True, unique=True),
        ),
    ]
