# Generated by Django 5.2.9 on 2026-08-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0009_attempt_routed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrafttaskattempt',
            name='cluster',
            field=models.CharField(blank=True, help_text='Requested routing target; null means whichever dispatcher claims it. Also the executor, except when an explicit broker override bypasses routing', max_length=150, null=True),
        ),
    ]
