# Generated by Django 5.2.9 on 2026-09-08 23:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0010_alter_qrafttaskattempt_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='qraftbatchmodel',
            name='hook_context',
            field=models.BooleanField(db_default=False, default=False, help_text='Whether workflow hooks receive a `context` keyword argument'),
        ),
        migrations.AddField(
            model_name='qraftbatchmodel',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='When the workflow last settled (settlement compare-and-swap column)', null=True),
        ),
        migrations.AddField(
            model_name='qraftbatchmodel',
            name='subject_id',
            field=models.CharField(blank=True, help_text='Identifier of the domain entity, as a string', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qraftbatchmodel',
            name='subject_type',
            field=models.CharField(blank=True, help_text="Kind of domain entity this work is for (e.g. 'worksheet')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qraftchainmodel',
            name='hook_context',
            field=models.BooleanField(db_default=False, default=False, help_text='Whether workflow hooks receive a `context` keyword argument'),
        ),
        migrations.AddField(
            model_name='qraftchainmodel',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='When the workflow last settled (settlement compare-and-swap column)', null=True),
        ),
        migrations.AddField(
            model_name='qraftchainmodel',
            name='subject_id',
            field=models.CharField(blank=True, help_text='Identifier of the domain entity, as a string', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qraftchainmodel',
            name='subject_type',
            field=models.CharField(blank=True, help_text="Kind of domain entity this work is for (e.g. 'worksheet')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qraftitermodel',
            name='hook_context',
            field=models.BooleanField(db_default=False, default=False, help_text='Whether workflow hooks receive a `context` keyword argument'),
        ),
        migrations.AddField(
            model_name='qraftitermodel',
            name='settled_at',
            field=models.DateTimeField(blank=True, help_text='When the workflow last settled (settlement compare-and-swap column)', null=True),
        ),
        migrations.AddField(
            model_name='qraftitermodel',
            name='subject_id',
            field=models.CharField(blank=True, help_text='Identifier of the domain entity, as a string', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qraftitermodel',
            name='subject_type',
            field=models.CharField(blank=True, help_text="Kind of domain entity this work is for (e.g. 'worksheet')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='hook_context',
            field=models.BooleanField(db_default=False, default=False, help_text='Whether success/failure hooks receive a `context` keyword argument'),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='subject_id',
            field=models.CharField(blank=True, help_text='Identifier of the domain entity, as a string', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='subject_type',
            field=models.CharField(blank=True, help_text="Kind of domain entity this work is for (e.g. 'worksheet')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='enqueued_at',
            field=models.DateTimeField(blank=True, help_text='When the attempt was handed to the broker', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='progress',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Attempt-reported progress payload (current/total/message)', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='progress_advanced_at',
            field=models.DateTimeField(blank=True, help_text='Last time current/total changed', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='progress_reported_at',
            field=models.DateTimeField(blank=True, help_text='Last report_progress() call from this attempt', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='trace_context',
            field=models.CharField(blank=True, help_text='W3C traceparent captured at enqueue, when a span was current', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='qrafttask',
            name='progress',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="Snapshot of the latest attempt's progress (current/total/message)", null=True),
        ),
        migrations.AddIndex(
            model_name='qrafttask',
            index=models.Index(fields=['subject_type', 'subject_id'], name='qraft_task_subject_idx'),
        ),
    ]
