# Generated by Django 5.2.9 on 2026-09-09 05:46

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0011_subjects_progress_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='qraftbatchmodel',
            name='stage',
            field=models.CharField(blank=True, help_text='Stage of the run this work is correlated with', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qraftchainmodel',
            name='stage',
            field=models.CharField(blank=True, help_text='Stage of the run this work is correlated with', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qraftitermodel',
            name='stage',
            field=models.CharField(blank=True, help_text='Stage of the run this work is correlated with', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='stage',
            field=models.CharField(blank=True, help_text='Stage of the run this work is correlated with', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='QraftRun',
            fields=[
                ('subject_type', models.CharField(blank=True, help_text="Kind of domain entity this work is for (e.g. 'worksheet')", max_length=100, null=True)),
                ('subject_id', models.CharField(blank=True, help_text='Identifier of the domain entity, as a string', max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, help_text="Execution fingerprint (e.g. 'shadow', 'parity'); a metric label", max_length=50, null=True)),
                ('revision', models.CharField(blank=True, help_text='Pipeline or input revision; never a metric label', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Application data; never a metric label', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned')], db_index=True, default='open', help_text='Current run status', max_length=16)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now, help_text='When the work this run covers began; may be backdated')),
                ('settled_at', models.DateTimeField(blank=True, help_text='When the run settled (settlement compare-and-swap column)', null=True)),
                ('overdue_flagged_at', models.DateTimeField(blank=True, help_text='When the overdue sweep first flagged this run', null=True)),
                ('on_settled', models.CharField(blank=True, help_text='Dotted path to the durable completion hook', max_length=256, null=True)),
                ('on_settled_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Keyword arguments for the completion hook')),
                ('summary', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Snapshot of stages, durations and usage, written at settlement', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('previous_run', models.ForeignKey(blank=True, help_text='The run this one reruns', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='qraft.qraftrun')),
            ],
            options={
                'verbose_name': 'Qraft Run',
                'verbose_name_plural': 'Qraft Runs',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='qraftbatchmodel',
            name='run',
            field=models.ForeignKey(blank=True, help_text='Run this work is correlated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_members', to='qraft.qraftrun'),
        ),
        migrations.AddField(
            model_name='qraftchainmodel',
            name='run',
            field=models.ForeignKey(blank=True, help_text='Run this work is correlated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_members', to='qraft.qraftrun'),
        ),
        migrations.AddField(
            model_name='qraftitermodel',
            name='run',
            field=models.ForeignKey(blank=True, help_text='Run this work is correlated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_members', to='qraft.qraftrun'),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='run',
            field=models.ForeignKey(blank=True, help_text='Run this work is correlated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_members', to='qraft.qraftrun'),
        ),
        migrations.CreateModel(
            name='QraftRunStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Stage name, unique per run', max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Declaration order, for display only; Qraft enforces no ordering')),
                ('unit_type', models.CharField(blank=True, choices=[('task', 'Task'), ('chain', 'Chain'), ('iter', 'Iter'), ('batch', 'Batch')], help_text='What kind of row owns this stage', max_length=8, null=True)),
                ('unit_id', models.UUIDField(blank=True, help_text='The bound task or workflow', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('bound', 'Bound'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', help_text='Current stage status', max_length=16)),
                ('skip_reason', models.TextField(blank=True, null=True)),
                ('bound_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(help_text='Run that declared this stage', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='qraft.qraftrun')),
            ],
            options={
                'verbose_name': 'Qraft Run Stage',
                'verbose_name_plural': 'Qraft Run Stages',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='qraftrun',
            index=models.Index(fields=['subject_type', 'subject_id'], name='qraft_run_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='qraftrunstage',
            constraint=models.UniqueConstraint(fields=('run', 'name'), name='unique_stage_name_per_run'),
        ),
    ]
