# Generated by Django 5.2.9 on 2026-09-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0012_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrafttask',
            name='stall_after',
            field=models.PositiveIntegerField(blank=True, help_text='Seconds without progress advancing before an attempt is flagged as a suspected stall; null disables the check', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='stall_suspected_at',
            field=models.DateTimeField(blank=True, help_text='When the reaper first flagged this attempt as a suspected stall', null=True),
        ),
    ]
