# Generated by Django 5.2.9 on 2026-09-09 09:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0013_stall_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='qraftrun',
            name='budgets',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Remaining request allowance per budget key (whole counts)', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='execution_count',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text='Deliveries of this attempt a worker has begun executing'),
        ),
    ]
