# Generated by Django 6.0.8 on 2026-09-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0014_execution_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='returned_at',
            field=models.DateTimeField(blank=True, help_text='When the target function returned or raised, stamped by qraft.runner.run_task inside the worker. Set with success still NULL means the work ran and its result never reached the monitor', null=True),
        ),
    ]
