# Generated by Django 6.0.8 on 2026-09-09 21:23

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0015_qrafttaskattempt_returned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='QraftGraph',
            fields=[
                ('subject_type', models.CharField(blank=True, help_text="Kind of domain entity this work is for (e.g. 'worksheet')", max_length=100, null=True)),
                ('subject_id', models.CharField(blank=True, help_text='Identifier of the domain entity, as a string', max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, help_text="Execution fingerprint (e.g. 'shadow', 'parity'); a metric label", max_length=50, null=True)),
                ('revision', models.CharField(blank=True, help_text='Pipeline or input revision; never a metric label', max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Application data; never a metric label', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='running', help_text='Current graph status', max_length=16)),
                ('generation', models.PositiveIntegerField(db_default=1, default=1, help_text='Bumped on resume; stale-generation completions are dropped')),
                ('cluster', models.CharField(blank=True, help_text='Default cluster for nodes that name none', max_length=150, null=True)),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now, help_text='When the work this graph covers began; may be backdated')),
                ('settled_at', models.DateTimeField(blank=True, help_text='When the graph settled (settlement compare-and-swap column)', null=True)),
                ('resumed_at', models.DateTimeField(blank=True, help_text='When the graph was last resumed', null=True)),
                ('overdue_flagged_at', models.DateTimeField(blank=True, help_text='When the overdue sweep first flagged this graph', null=True)),
                ('on_settled', models.CharField(blank=True, help_text='Dotted path to the durable completion hook', max_length=256, null=True)),
                ('on_settled_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Keyword arguments for the completion hook')),
                ('budgets', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Remaining request allowance per budget key (whole counts)', null=True)),
                ('summary', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Snapshot of nodes, durations and usage, written at settlement', null=True)),
                ('request_key', models.CharField(blank=True, help_text='Submission idempotency key; same key and plan returns the graph', max_length=255, null=True, unique=True)),
                ('plan_hash', models.CharField(blank=True, help_text='Fingerprint of the node topology at start()', max_length=64, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qraft Graph',
                'verbose_name_plural': 'Qraft Graphs',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='QraftGraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Node key, unique per graph', max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Declaration order within the same depth')),
                ('depth', models.PositiveSmallIntegerField(default=0, help_text='Longest path from a root, derived at start()')),
                ('after', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Node keys that must succeed or be skipped before this runs')),
                ('func', models.CharField(help_text='Dotted path to the task function', max_length=256)),
                ('task_args', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Frozen positional arguments')),
                ('task_kwargs', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Frozen keyword arguments')),
                ('options', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Frozen qraft options (retry, cluster, hooks, ...)')),
                ('recovery', models.CharField(choices=[('transactional', 'Transactional'), ('idempotent', 'Idempotent'), ('manual', 'Manual')], help_text="How this node's completion may be trusted on resume", max_length=16)),
                ('generation', models.PositiveIntegerField(db_default=1, default=1, help_text='Bumped on resume; the task FK is the generation marker')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', help_text='Current node status', max_length=16)),
                ('skip_reason', models.TextField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Qraft Graph Node',
                'verbose_name_plural': 'Qraft Graph Nodes',
                'ordering': ['depth', 'position', 'key'],
            },
        ),
        migrations.RemoveIndex(
            model_name='qraftrun',
            name='qraft_run_subject_idx',
        ),
        migrations.RemoveField(
            model_name='qrafttask',
            name='run',
        ),
        migrations.RemoveField(
            model_name='qraftitermodel',
            name='run',
        ),
        migrations.RemoveField(
            model_name='qraftchainmodel',
            name='run',
        ),
        migrations.RemoveField(
            model_name='qraftbatchmodel',
            name='run',
        ),
        migrations.RemoveConstraint(
            model_name='qraftrunstage',
            name='unique_stage_name_per_run',
        ),
        migrations.RemoveField(
            model_name='qraftbatchmodel',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='qraftchainmodel',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='qraftitermodel',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='qrafttask',
            name='stage',
        ),
        migrations.AddField(
            model_name='qraftbatchmodel',
            name='node',
            field=models.CharField(blank=True, help_text='Node key within the graph, for correlation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qraftchainmodel',
            name='node',
            field=models.CharField(blank=True, help_text='Node key within the graph, for correlation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qraftitermodel',
            name='node',
            field=models.CharField(blank=True, help_text='Node key within the graph, for correlation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='node',
            field=models.CharField(blank=True, help_text='Node key within the graph, for correlation', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='output_committed_at',
            field=models.DateTimeField(blank=True, help_text='When a transactional node published its receipt (phase 3)', null=True),
        ),
        migrations.AddField(
            model_name='qraftgraph',
            name='previous_graph',
            field=models.ForeignKey(blank=True, help_text='The graph this one reruns', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='qraft.qraftgraph'),
        ),
        migrations.AddField(
            model_name='qraftbatchmodel',
            name='graph',
            field=models.ForeignKey(blank=True, help_text='Graph this work is correlated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_members', to='qraft.qraftgraph'),
        ),
        migrations.AddField(
            model_name='qraftchainmodel',
            name='graph',
            field=models.ForeignKey(blank=True, help_text='Graph this work is correlated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_members', to='qraft.qraftgraph'),
        ),
        migrations.AddField(
            model_name='qraftitermodel',
            name='graph',
            field=models.ForeignKey(blank=True, help_text='Graph this work is correlated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_members', to='qraft.qraftgraph'),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='graph',
            field=models.ForeignKey(blank=True, help_text='Graph this work is correlated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_members', to='qraft.qraftgraph'),
        ),
        migrations.AddField(
            model_name='qraftgraphnode',
            name='graph',
            field=models.ForeignKey(help_text='Graph that declared this node', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='qraft.qraftgraph'),
        ),
        migrations.AddField(
            model_name='qraftgraphnode',
            name='task',
            field=models.ForeignKey(blank=True, help_text="The current generation's task", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_node_binding', to='qraft.qrafttask'),
        ),
        migrations.AddField(
            model_name='qrafttask',
            name='graph_node',
            field=models.ForeignKey(blank=True, help_text='The node this task is the current execution of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='qraft.qraftgraphnode'),
        ),
        migrations.RemoveField(
            model_name='qraftrun',
            name='previous_run',
        ),
        migrations.RemoveField(
            model_name='qraftrunstage',
            name='run',
        ),
        migrations.AddIndex(
            model_name='qraftgraph',
            index=models.Index(fields=['subject_type', 'subject_id'], name='qraft_graph_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='qraftgraphnode',
            constraint=models.UniqueConstraint(fields=('graph', 'key'), name='unique_node_key_per_graph'),
        ),
        migrations.DeleteModel(
            name='QraftRun',
        ),
        migrations.DeleteModel(
            name='QraftRunStage',
        ),
    ]
