# Generated by Django 6.0.8 on 2026-09-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0016_graphs'),
    ]

    operations = [
        migrations.AddField(
            model_name='qraftgraphnode',
            name='receipt',
            field=models.JSONField(blank=True, help_text="What the node published, written in the same transaction as the application's own writes. Its presence is the proof the effect committed; cleared when the node is re-run", null=True),
        ),
        migrations.AddField(
            model_name='qraftgraphnode',
            name='receipt_attempt_id',
            field=models.UUIDField(blank=True, help_text='The attempt that published the receipt', null=True),
        ),
        migrations.AddField(
            model_name='qrafttaskattempt',
            name='output_committed_at',
            field=models.DateTimeField(blank=True, help_text="When this attempt published a graph node's output through qraft.graphs.publish(). Set with success still NULL means the work committed and only its result was lost", null=True),
        ),
    ]
