# Generated by Django 6.0.8 on 2026-09-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0017_completion_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='qraftgraphnode',
            name='requires_approval',
            field=models.BooleanField(db_default=False, default=False, help_text='Park the node for a person once its dependencies are met'),
        ),
        migrations.AlterField(
            model_name='qraftgraph',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('waiting_approval', 'Waiting approval')], db_index=True, default='running', help_text='Current graph status', max_length=16),
        ),
        migrations.AlterField(
            model_name='qraftgraphnode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped'), ('waiting_approval', 'Waiting approval')], default='pending', help_text='Current node status', max_length=16),
        ),
    ]
