# Generated by Django 6.0.8 on 2026-09-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0018_node_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowhookdispatch',
            name='hook_type',
            field=models.CharField(help_text="Type of hook: 'success', 'failure', or 'settled'", max_length=10),
        ),
        migrations.AlterField(
            model_name='workflowhookdispatch',
            name='workflow_id',
            field=models.UUIDField(db_index=True, help_text='UUID of the workflow (chain/iter/batch/graph)'),
        ),
        migrations.AlterField(
            model_name='workflowhookdispatch',
            name='workflow_type',
            field=models.CharField(help_text="Type of workflow: 'chain', 'iter', 'batch', or 'graph'", max_length=10),
        ),
    ]
