# Generated by Django 5.2.9 on 2026-09-10 14:46

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrate_dispatch_generations(apps, schema_editor):
    Graph = apps.get_model("qraft", "QraftGraph")
    Dispatch = apps.get_model("qraft", "WorkflowHookDispatch")
    alias = schema_editor.connection.alias
    for graph in Graph.objects.using(alias).all().iterator():
        Dispatch.objects.using(alias).filter(
            workflow_type="graph", workflow_id=graph.pk
        ).update(generation=graph.generation)


class Migration(migrations.Migration):

    dependencies = [
        ('qraft', '0019_graph_hook_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='QraftGraphSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('hook_path', models.CharField(max_length=256)),
                ('hook_kwargs', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('context', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='workflowhookdispatch',
            name='unique_workflow_hook_dispatch',
        ),
        migrations.AddField(
            model_name='workflowhookdispatch',
            name='generation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='workflowhookdispatch',
            constraint=models.UniqueConstraint(fields=('workflow_type', 'workflow_id', 'hook_type', 'generation'), name='unique_workflow_hook_dispatch'),
        ),
        migrations.AddField(
            model_name='qraftgraphsettlement',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='qraft.qraftgraph'),
        ),
        migrations.AddConstraint(
            model_name='qraftgraphsettlement',
            constraint=models.UniqueConstraint(fields=('graph', 'generation'), name='unique_graph_settlement'),
        ),
        migrations.RunPython(migrate_dispatch_generations, migrations.RunPython.noop),
    ]
